// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2026_ruangkita_backend.Data;

#nullable disable

namespace _2026_ruangkita_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209102304_AddStatusHistoryTable")]
    partial class AddStatusHistoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("_2026_ruangkita_backend.Models.Borrowing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Borrowings");
                });

            modelBuilder.Entity("_2026_ruangkita_backend.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Facility")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            Facility = "AC, Proyektor, komputer",
                            Name = "Lab komputer"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 40,
                            Facility = "AC, Whiteboard",
                            Name = "B-201"
                        });
                });

            modelBuilder.Entity("_2026_ruangkita_backend.Models.StatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BorrowingId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatusHistoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BorrowingId");

                    b.HasIndex("StatusHistoryId");

                    b.ToTable("StatusHistories");
                });

            modelBuilder.Entity("_2026_ruangkita_backend.Models.Borrowing", b =>
                {
                    b.HasOne("_2026_ruangkita_backend.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("_2026_ruangkita_backend.Models.StatusHistory", b =>
                {
                    b.HasOne("_2026_ruangkita_backend.Models.Borrowing", "Borrowing")
                        .WithMany("StatusHistories")
                        .HasForeignKey("BorrowingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2026_ruangkita_backend.Models.StatusHistory", null)
                        .WithMany("StatusHistories")
                        .HasForeignKey("StatusHistoryId");

                    b.Navigation("Borrowing");
                });

            modelBuilder.Entity("_2026_ruangkita_backend.Models.Borrowing", b =>
                {
                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("_2026_ruangkita_backend.Models.StatusHistory", b =>
                {
                    b.Navigation("StatusHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
